KERNEL_PREBUILT_PATH := device/xiaomi/whyred-kernel

# Headers
PRODUCT_VENDOR_KERNEL_HEADERS := $(KERNEL_PREBUILT_PATH)/sdm660/kernel-headers

# Kernel
LOCAL_KERNEL := $(KERNEL_PREBUILT_PATH)/Image.gz-dtb
PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

# Kernel Modules
KERNEL_MODULES := $(wildcard $(KERNEL_PREBUILT_PATH)/*.ko)
BOARD_VENDOR_KERNEL_MODULES := $(KERNEL_MODULES)

# Soong namespaces
PRODUCT_SOONG_NAMESPACES += \
    $(KERNEL_PREBUILT_PATH)
